POST http://localhost:5555/auth/login
Content-Type: application/json

{
    "email": "ajay123@gmail.com",
    "password": "ajay123"
}

###
POST http://localhost:5555/auth/signup
Content-Type: application/json

{
    "name": "Ajay",
    "email": "ajay123@gmail.com",
    "phoneNumber": "1234567890",
    "password": "ajay123"
}

###
GET http://localhost:5555/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MjBmZWNmN2ExYTI0ODNhNGQwNjhmMyIsImlhdCI6MTY5NzI2Mzk0OCwiZXhwIjoxNjk3MzUwMzQ4fQ.Vkg4UPYL0tvlwo4bzAx5w0dvqczndeHTkCoup5SmB34

###
GET http://localhost:5555/api/movies-show?genre=&rating=&views=&languages=&original_language=&category=&studio=&director=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MjBmZWNmN2ExYTI0ODNhNGQwNjhmMyIsImlhdCI6MTY5NzI2Mzk0OCwiZXhwIjoxNjk3MzUwMzQ4fQ.Vkg4UPYL0tvlwo4bzAx5w0dvqczndeHTkCoup5SmB34

###
GET http://localhost:5555/api/movies-shows-details/65266c9c694115e99078a3b2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MjBmZWNmN2ExYTI0ODNhNGQwNjhmMyIsImlhdCI6MTY5NzI2Mzk0OCwiZXhwIjoxNjk3MzUwMzQ4fQ.Vkg4UPYL0tvlwo4bzAx5w0dvqczndeHTkCoup5SmB34

###
GET http://localhost:5555/api/news?channel_name=&news_category=&news_type=&news_tag=&language=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MjBmZWNmN2ExYTI0ODNhNGQwNjhmMyIsImlhdCI6MTY5NzI2Mzk0OCwiZXhwIjoxNjk3MzUwMzQ4fQ.Vkg4UPYL0tvlwo4bzAx5w0dvqczndeHTkCoup5SmB34

###
GET http://localhost:5555/api/news-details/652642633887528fb86136c3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MjBmZWNmN2ExYTI0ODNhNGQwNjhmMyIsImlhdCI6MTY5NzI2Mzk0OCwiZXhwIjoxNjk3MzUwMzQ4fQ.Vkg4UPYL0tvlwo4bzAx5w0dvqczndeHTkCoup5SmB34

###
GET http://localhost:5555/api/sports?matchDate=&sportType=&tournamentName=&team1=&team2=&votes=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MjBmZWNmN2ExYTI0ODNhNGQwNjhmMyIsImlhdCI6MTY5NzI2Mzk0OCwiZXhwIjoxNjk3MzUwMzQ4fQ.Vkg4UPYL0tvlwo4bzAx5w0dvqczndeHTkCoup5SmB34

###
GET http://localhost:5555/api/sports-details/652694def30e4b6e5b414751
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MjBmZWNmN2ExYTI0ODNhNGQwNjhmMyIsImlhdCI6MTY5NzI2Mzk0OCwiZXhwIjoxNjk3MzUwMzQ4fQ.Vkg4UPYL0tvlwo4bzAx5w0dvqczndeHTkCoup5SmB34




